name: Build Android APK with Buildozer Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer Action
        uses: ArtemSBulgakov/buildozer-action@v1.7.0  # 官方最新稳定版
        with:
          command: android debug  # 执行 Android 调试版打包
          buildozer_version: stable  # 使用稳定版 Buildozer
          # 若需要指定 Python 版本（可选，默认适配当前环境）
          python_version: 3.8
          # 挂载项目目录到容器（默认已配置，确保代码能被访问）
          workdir: .

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk  # 打包生成的 APK 路径（与 buildozer.spec 中 bin_dir 一致）
