姓名: 将Kivy应用程序自动构建到安装包
# 触发条件：推送代码或合并PR时运行
在……之上:
推:
分支机构:
      - 主要的
      - 掌握
pull_request:
分支机构:
      - 主要的
      - 掌握

工作:
build-android:
连续的: Ubuntu-最新版本
步骤:
      - 姓名: 签出代码
uses: 操作/结帐@v4
      - 姓名: 安装构建器和依赖项
跑: |
sudo apt-获取更新
sudo apt-get install-y build-基本python3-python3-dev python3-pip virtualenv
PIP安装造壁机
      - 姓名: 使用Buildozer构建安装包
跑: |
#这里假设buildozer.spec在仓库根目录，若不在需调整路径
Buildozer-v android调试
