name: Simple File List Check
# 触发条件设置为在 main 分支有推送操作时运行
on:
  push:
    branches:
      - main

jobs:
  list-files:
    runs-on: ubuntu - latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: List Files
        run: |
          ls -la
