name: Build Kivy App to APK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: 缓存Python依赖
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 安装基础依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev python3-pip virtualenv libssl-dev libffi-dev libsqlite3-dev zlib1g-dev
          # 锁定buildozer和python-for-android版本，避免兼容性问题
          pip install buildozer==1.5.0 python-for-android==2023.11.18

      - name: 安装Python项目依赖
        run: |
          # 明确指定kivy版本，确保安装成功
          pip install kivy==2.3.0
          # 确认kivy安装状态（关键：验证是否真的安装成功）
          pip list | grep kivy
          # 若有requirements.txt则取消注释，若无则删除此行
          # pip install -r requirements.txt

      - name: 安装Cython
        run: pip install cython==0.29.36  # 锁定Cython版本，与kivy兼容

      - name: 设置 ANDROID_HOME 环境变量
        run: echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV

      - name: 安装 Android SDK 命令行工具
        run: |
          mkdir -p $HOME/.android/cmdline-tools
          cd $HOME/.android/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
          mv cmdline-tools $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest
          export PATH=$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$PATH
          yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: 兼容 Buildozer 的 sdkmanager 软链接
        run: |
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin
          ln -sf $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

      - name: 构建APK
        run: |
          # 输出已安装的Python包列表，便于调试依赖问题
          pip freeze
          buildozer -v android debug

      - name: 上传APK文件
        uses: actions/upload-artifact@v4
        with:
          name: apk-file
          path: bin/*.apk
