姓名: 自动打包Kivy应用为APK

# 触发条件：推送代码或合并PR时运行
在……之上:
推:
分支机构: [主要的,掌握]  # 监听主分支的推送
pull_request:
分支机构: [主要的,掌握]  #监听主分支的PR

工作:
build-android:
连续的: Ubuntu-最新#使用乌本图系统运行
步骤:
      - 姓名: 拉取代码仓库
uses: 操作/结帐@v4# 拉取当前仓库代码

      - 姓名: 用Buildozer打包安卓应用
uses: ArtemSBulgakov/buildozer-action@v1
身份标识: Buildozer
和……一起:
          #【必须修改】buildozer.spec所在的文件夹路径
          #例如：若文件在项目根目录填"."，在"app"文件夹填"app"
WORKDIR: "你的buildozer.spec所在目录"
          
          # 代码仓库根目录（一般无需修改，默认就是当前目录）
存储库根目录(_R): "."
          
          #Buildozer版本（推荐保持稳定的，即最新稳定版）
Buildozer_version: "稳定"
          
          #打包命令（默认是调试版，如需正式版可改为"Buildozer android版本”)
命令: "buildozer android调试"

      - 姓名: 上传打包好的APK
uses: 操作/上载工件@v4
和……一起:
姓名: 安卓安装包# 下载时显示的文件名
路径: ${{steps.buildozer.outputs.filename}}  # 自动获取打包后的APK路径
